SET SCHEMA FN2MI0700013;

CREATE OR REPLACE MODULE PROJ;

--Function 1 that returns count of orders of a client by phone number
ALTER MODULE PROJ DROP FUNCTION F_ORDERS_COUNT(CHAR(12));
ALTER MODULE PROJ PUBLISH
FUNCTION F_ORDERS_COUNT(IN PHONE_NUM CHAR(12))
RETURNS INT
BEGIN
    DECLARE ORDERS_COUNT INT DEFAULT 0;
    SET ORDERS_COUNT = (SELECT COUNT(*) FROM ORDER WHERE CLIENT_PHONE_NUMBER = PHONE_NUM);
    RETURN ORDERS_COUNT;
end;

BEGIN
    DECLARE F_PHONE_NUM CHAR(12);
    DECLARE F_RESULT INT;
    SET F_PHONE_NUM = ?; -- INPUT FROM KEYBOARD
    SET F_RESULT = (SELECT FN2MI0700013.PROJ.F_ORDERS_COUNT(F_PHONE_NUM) FROM SYSIBM.SYSDUMMY1);
    CALL DBMS_OUTPUT.PUT_LINE('ORDER COUNT OF CLIENT WITH PHONE NUMBER ' || F_PHONE_NUM || ' IS ' || F_RESULT);
end;

--Function 2 which returns how many pizzas contain some product

ALTER MODULE PROJ DROP FUNCTION F_PIZZA_WITH_PRODUCT_CNT(VARCHAR(30));
ALTER MODULE PROJ PUBLISH FUNCTION F_PIZZA_WITH_PRODUCT_CNT(IN PRODUCT VARCHAR(30))
RETURNS INT
BEGIN
    DECLARE V_PIZZA_CNT INT DEFAULT 0;
    SET V_PIZZA_CNT = (SELECT COUNT(*) FROM PIZZACONTENTS WHERE PRODUCT_NAME = PRODUCT);

    RETURN V_PIZZA_CNT;

end;

BEGIN
    DECLARE F_PRODUCT VARCHAR(30);
    DECLARE F_RESULT INT;
    SET F_PRODUCT = ?; -- INPUT FROM KEYBOARD
        SET F_RESULT = (SELECT FN2MI0700013.PROJ.F_PIZZA_WITH_PRODUCT_CNT(F_PRODUCT) FROM SYSIBM.SYSDUMMY1);
        CALL DBMS_OUTPUT.PUT_LINE('NUMBER OF PIZZAS WHICH CONTAIN PRODUCT ' || F_PRODUCT || ' IS ' || F_RESULT);
end;




