 SET SCHEMA FN2MI0700013;

---Tables----
CREATE TABLE PIZZA(
    pizza_id CHAR(5) NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    price FLOAT CHECK( PRICE > 0 ) NOT NULL,
    weight INT CHECK( WEIGHT > 0 ) NOT NULL
);

CREATE TABLE DRINKS(
    drink_id CHAR(5) NOT NULL,
    name VARCHAR(30) NOT NULL UNIQUE,
    price FLOAT NOT NULL CHECK( PRICE > 0 ),
    quantity FLOAT NOT NULL CHECK( QUANTITY > 0 )
);

CREATE TABLE CLIENT(
    name VARCHAR(50) NOT NULL,
    address VARCHAR(150) NOT NULL,
    phone_number CHAR(12) NOT NULL
);

CREATE TABLE PRODUCTS(
    name VARCHAR(30) NOT NULL,
    price FLOAT NOT NULL CHECK( PRICE > 0),
    weight FLOAT NOT NULL CHECK( WEIGHT > 0 )
);

CREATE TABLE ORDER(
    client_phone_number CHAR(12) NOT NULL UNIQUE,
    order_date DATE NOT NULL
);

CREATE TABLE PizzaContents(
    pizzaID CHAR(5) NOT NULL,
    product_name VARCHAR(30)
);

CREATE TABLE AddExtraToPizza(
    pizza_id CHAR(5) NOT NULL,
    extras_name VARCHAR(30) NOT NULL,
    order DATE NOT NULL,
    client_phone_num CHAR(10),
    extra_quantity INT CHECK( extra_quantity > 0) NOT NULL
);
CREATE TABLE AddDrinkToOrder(
    drink_id CHAR(5) NOT NULL,
    drink_quantity FLOAT NOT NULL CHECK( drink_quantity > 0 ),
    order DATE NOT NULL,
    client_phone_num CHAR(12)
);

CREATE TABLE AddPizzaToOrder(
    pizza_id CHAR(5) NOT NULL,
    pizza_quantity INT CHECK( pizza_quantity > 0 ) NOT NULL,
    order DATE NOT NULL,
    client_phone_num CHAR(12) NOT NULL
);

----Constraints-----
ALTER TABLE PIZZA ADD CONSTRAINT PK_PIZZA PRIMARY KEY(pizza_id);

ALTER TABLE DRINKS ADD CONSTRAINT PK_DRINK PRIMARY KEY(drink_id);

ALTER TABLE CLIENT ADD CONSTRAINT PK_CLIENT PRIMARY KEY(phone_number);

ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCT PRIMARY KEY(name);

ALTER TABLE ORDER ADD CONSTRAINT PK_DATE PRIMARY KEY(order_date);
ALTER TABLE ORDER ADD CONSTRAINT UC_ORDER UNIQUE(client_phone_number);
ALTER TABLE ORDER ADD CONSTRAINT FK_CLIENT_NUMBER FOREIGN KEY(client_phone_number) REFERENCES CLIENT(phone_number);

ALTER TABLE PizzaContents ADD CONSTRAINT FK_PIZZA FOREIGN KEY(pizzaID) REFERENCES PIZZA(pizza_id);
ALTER TABLE PizzaContents ADD CONSTRAINT FK_CONTENTS FOREIGN KEY(product_name) REFERENCES PRODUCTS(name);

ALTER TABLE AddExtraToPizza ADD CONSTRAINT PK_EXTRA PRIMARY KEY(extra_quantity);
ALTER TABLE AddExtraToPizza ADD CONSTRAINT FK_CLIENT_NUMBER FOREIGN KEY(client_phone_num) REFERENCES ORDER(client_phone_number);
ALTER TABLE ADDEXTRATOPIZZA ADD CONSTRAINT FK_ORDER_DATE FOREIGN KEY(order) REFERENCES ORDER(order_date);
ALTER TABLE AddExtraToPizza ADD CONSTRAINT FK_PIZZA FOREIGN KEY(pizza_id) REFERENCES PIZZA(pizza_id);
ALTER TABLE AddExtraToPizza ADD CONSTRAINT FK_EXTRA_NAME FOREIGN KEY(extras_name) REFERENCES PRODUCTS(name);

ALTER TABLE AddDrinkToOrder ADD CONSTRAINT PK_ADD_DRINK PRIMARY KEY(drink_quantity);
ALTER TABLE AddDrinkToOrder ADD CONSTRAINT FK_DRINK FOREIGN KEY(drink_id) REFERENCES DRINKS(drink_id);
ALTER TABLE AddDrinkToOrder ADD CONSTRAINT FK_ORDER_DATE FOREIGN KEY(order) REFERENCES ORDER(order_date);
ALTER TABLE AddDrinkToOrder ADD CONSTRAINT FK_ORDER_DRINK_CLIENT_NUM FOREIGN KEY(client_phone_num) REFERENCES ORDER(client_phone_number);


ALTER TABLE AddPizzaToOrder ADD CONSTRAINT PK_ADD_PIZZA PRIMARY KEY(pizza_quantity);
ALTER TABLE AddPizzaToOrder ADD CONSTRAINT FK_PIZZA FOREIGN KEY(pizza_id) REFERENCES PIZZA(pizza_id);
ALTER TABLE AddPizzaToOrder ADD CONSTRAINT FK_ORDER_DATE FOREIGN KEY(order) REFERENCES ORDER(order_date);
ALTER TABLE AddPizzaToOrder ADD CONSTRAINT FK_CLIENT_NUM FOREIGN KEY(client_phone_num) REFERENCES ORDER(client_phone_number);















