SET SCHEMA FN2MI0700013;

--readonly заявка за поръчки
CREATE VIEW V_ORDER_DETAILS (ORDER_DATE, PHONE_NUMBER, DELIVERY_ADDRESS, DRINK, DRINK_QUANTITY, PIZZA, PIZZA_QUANTITY, EXTRA_NAME, EXTRA_QUANTITY) AS
SELECT O.ORDER_DATE, C.PHONE_NUMBER, C.ADDRESS, D.NAME, ADO.DRINK_QUANTITY, P.NAME, APO.PIZZA_QUANTITY, AXO.EXTRAS_NAME, AXO.EXTRA_QUANTITY
FROM ORDER O, CLIENT C, ADDDRINKTOORDER ADO, ADDPIZZATOORDER APO, DRINKS D, PIZZA P, ADDEXTRATOPIZZA AXO
WHERE O.ORDER_DATE = ADO.ORDER
AND O.ORDER_DATE = APO.ORDER
AND O.ORDER_DATE = AXO.ORDER
AND O.CLIENT_PHONE_NUMBER = C.PHONE_NUMBER
AND ADO.DRINK_ID = D.DRINK_ID
AND APO.PIZZA_ID = P.PIZZA_ID;

SELECT * FROM V_ORDER_DETAILS;


-- updatable
CREATE VIEW V_TOP_PIZZAS AS
SELECT *
FROM PIZZA
WHERE PRICE > 15;

SELECT PIZZA.NAME, PIZZA.PRICE, PIZZA.WEIGHT
FROM FN2MI0700013.PIZZA
WHERE PRICE > 15;

INSERT INTO V_TOP_PIZZAS(PIZZA_ID, NAME, PRICE, WEIGHT)
VALUES('12345', 'New York', 17.90, 500);

-- updatable with check
CREATE VIEW V_SOFIA_ORDERS AS
SELECT *
FROM CLIENT
WHERE ADDRESS LIKE '%Sofia'
WITH CHECK OPTION;

INSERT INTO V_SOFIA_ORDERS(NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Bocho Bochev', '11 Milin Kamak, Sofia', '359887112779');

INSERT INTO V_SOFIA_ORDERS(NAME, ADDRESS, PHONE_NUMBER)
VALUES ('Ganio Drumev', '42 Popska, Kaspichan','359887061498');


SELECT NAME, PRICE, QUANTITY FROM FN2MI0700013.DRINKS